name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          
      - name: Install Dependencies (Backend)
        run: |
          cd backend
          npm install

      - name: Install Dependencies (Frontend)
        run: |
          cd frontend
          npm install --force

      - name: Build Frontend
        run: |
          cd frontend
          npm run build
